### ISSUE TITLE
💻  Ver o comportamento da scroll view

### ISSUE THREAD

**Issue by thallissousa** [Hortali/Hortali-App#40]
No iPhone do Joca aconteceu da scroll rolar para os lados (mesmo comportamento que teve em algum dos testes que a gnt fez). 

Precisa analisar e ver quando que isso acontece. O iPhone 12 não acontece mas no do Joca que é o 11 pro max acontece.

Foto que o Joca mandou:

<p align="center">
<img  height=500px src="https://user-images.githubusercontent.com/48360732/196789039-fd3c2d81-62d8-46fa-8569-80de147dd305.png">
</p>

**Comment by Gui25Reis** [comment]
Scroll não está funcionando 100% quando. A nova lógica acabou não funcionando. Precisa repensar

**Comment by Gui25Reis** [comment]
A princípio o problema está na quantidade de linhas da label expandível. O problema parece não existir mais.
